
overlap: True
backbone: mit_b2
random_seed: 1


dataset:
  name: voc
  data_root: /mnt/hdd0/vclab_datasets/VOCdevkit/VOC2012
  num_classes: 21
  crop_size: 512
  resize_range: [512, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255
  batch_size: 8
  val_batch_size: 4

train:
  split: train_aug
  samples_per_gpu: 6
  epochs: 50
  eval_iters: 5000
  log_iters: 50

optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0